### ISSUE TITLE
R7RS support question

### ISSUE THREAD

**Issue by jpt4** [marcomaggi/vicare#79]
Is vicare scheme intended to be compliant with the R7RS standard, and if so, the small or the large?

**Comment by marcomaggi** [comment]
I have no intention of supporting R7RS.  See my [weblog](http://marcomaggi.github.io/weblog/2015-February-16.html) for an overview of what I think.  There is an abandoned [project](https://github.com/okuoku/r7rs-bridge) with the purpose of supporting R7 on top of R6; I know nothing about it.

**Comment by jpt4** [comment]
Thank you for answering my question.
