### ISSUE TITLE
texinfo does not like @meta as argument for @table

### ISSUE THREAD

**Issue by stefanhusmann** [marcomaggi/vicare#81]
I encountered a problem compiling expander.texi with a texinfo 6 from svn trunk. The @table macro does not accept @meta as an argument. I worked around this with 

sed -i 's+@table @meta+@table @code+' doc/expander.texi

But I do not know if that format is desirable for you.

**Comment by marcomaggi** [comment]
Thanks for the report.  It should be fixed in the head of the ```master``` branch.
