### ISSUE TITLE
configure broken?

### ISSUE THREAD

**Issue by piantado** [marcomaggi/vicare#89]
I can't seem to get the ./configure to run in the development version.

**Comment by marcomaggi** [comment]
> I can't seem to get the ./configure to run in the development version.

Unlikely.  What error do you get when running:
```
$ ./configure
```
?

**Comment by piantado** [comment]
$ ./configure
bash: ./configure: No such file or directory
$ ./configure.sh 
++ prefix=/usr/local
++ test -d /lib64
++ libdir=/usr/local/lib64
++ LIBFFI_VERSION=3.2.1
++ LIBFFI_INCLUDEDIR=/usr/local/lib64/libffi-3.2.1/include
++ VFLAGS=-O2
++ ../configure --enable-maintainer-mode --config-cache --cache-file=../config.cache --prefix=/usr/local --libdir=/usr/local/lib64 --enable-binfmt --enable-time-tests --enable-scheme-script --with-pthread 'CFLAGS=-O3 -pedantic' CPPFLAGS=-I/usr/local/lib64/libffi-3.2.1/include VFLAGS=-O2
./configure.sh: line 17: ../configure: No such file or directory

**Comment by marcomaggi** [comment]
I gather this is from the repository checkout of the `master` branch.  Have you followed the instructions in the `README` file about building from a repository checkout?  First run `sh autogen.sh`, then `configure` with maintainer mode enabled, ...

**Comment by piantado** [comment]
Yikes, sorry about that. Yes, I didn't read down further in the readme.
