### ISSUE TITLE
Importing libraries

### ISSUE THREAD

**Issue by stefanhusmann** [marcomaggi/vicare#91]
I am using Vicare Scheme in the stable version from bitbucket and the most recent github version on a Arch Linux system (64 bit).
The following is happening with the unstable version
``` lisp
> vicare
Vicare Scheme version 0.4d0, 64-bit
Build 2016-04-27

Copyright (c) 2006-2010 Abdulaziz Ghuloum and contributors
Copyright (c) 2011-2015 Marco Maggi and contributors

vicare> (import (srfi :19))
Unhandled exception
Condition components:
1. &error
2. &who: expander
3. &message: "cannot locate library"
4. &library-resolution:
library: (srfi :19)
files: ()
vicare>
```
If I run the unstable version with -L /usr/lib/vicare-scheme/ or the stable version, everything seems fine.
``` lisp
Vicare Scheme version 0.4d0, 64-bit
Build 2016-04-27

Copyright (c) 2006-2010 Abdulaziz Ghuloum and contributors
Copyright (c) 2011-2015 Marco Maggi and contributors

vicare> (import (srfi :19))
vicare> 
```

**Comment by marcomaggi** [comment]
I cannot replicate the problem.  Actually, there is no _stable_ version.  When I build from the `0.4pre4` tarball with:
```
$ ./configure --prefix=/usr/local --libdir=/usr/local/lib64
```
I leave the environment variables `VICARE_LIBRARY_PATH` and `VICARE_SOURCE_PATH` empty; then I run the REPL and I see:
```
vicare> (import (vicare libraries))
vicare> (library-source-search-path)
$1 = ()
vicare> (library-binary-search-path)
$1 = ("/usr/local/lib64/vicare-scheme")
vicare> (import (srfi :19))
vicare> (current-date)
$1 = (struct date (nanosecond 197758000) (second 1) (minute 47)
  (hour 6) (day 8) (month 5) (year 2016) (zone-offset 3600))
vicare> 
```
What do you see?

**Comment by stefanhusmann** [comment]
The tarball is fine, the repo version seems to need the -L option to find the libs.

**Comment by marcomaggi** [comment]
By _repo version_ you mean the HEAD of the `master` branch?  And what do you see when you build it, install it, and inspect the libraries search paths?  Try to run `vicare` with the options:
```
$ vicare  --option print-loaded-libraries --option debug-messages
```
and then load `(srfi :19)`; what is the output?  Is this library the only one having problems?  The other libraries load fine?

**Comment by stefanhusmann** [comment]
I did so, and it seems that explicitely setting exec-prefix at build time as configure-option fixes the issue.
[file.txt](https://github.com/marcomaggi/vicare/files/253923/file.txt)
But shouldn't be $exec_prefix equal to $prefix if not set explicitely?

**Comment by marcomaggi** [comment]
The problem should be in the was `@`-substitutions are performed in the file `ikarus.config.scm`.  It should be fixed in the HEAD of the `master` branch.

**Comment by stefanhusmann** [comment]
The file ikarus.config.scm is missing, did you push it?

**Comment by marcomaggi** [comment]
Makefile problem.  Should be fixed now.

**Comment by stefanhusmann** [comment]
Thanks, all is fixed now.

**Comment by marcomaggi** [comment]
Thank you for reporting and investigating.
