### ISSUE TITLE
Update irregex to 0.9.6 (security update)

### ISSUE THREAD

**Issue by sjamaan** [marcomaggi/vicare#92]
Hi, 

A resource exhaustion vulnerability was found in the way irregex compiles nested `+` patterns. Please see [this announcement/CVE request](http://www.openwall.com/lists/oss-security/2016/12/14/18) (CVE assignment is currently pending).

Updating Irregex to 0.9.6 should fix this issue. See [this changeset](https://github.com/ashinn/irregex/commit/a16ffc86eca15fca9e40607d41de3cea9cf868f1) for more information on the fix.

Regards,
Peter Bex

**Comment by marcomaggi** [comment]
I have updated in the `master` branch.  Thanks.
