### ISSUE TITLE
Compiler error with fxxor

### ISSUE THREAD

**Issue by weinholt** [marcomaggi/vicare#94]
I am using Vicare Scheme 0.4d1, 64-bit on a Debian GNU/Linux 8.7 amd64 system.

I tried my x86 emulator with Vicare and it crashed on an internal compiler error. Here's a minimized test case (the definition of foo must be separate so that cp0 doesn't inline it):

```Scheme
(define (foo) 0)

(lambda ()
  (let* ((t0 (foo))
         (t1 18)
         (tmp (fx- t0 t1))
         (fl-OF (lambda ()
                  (fxand (fxxor t0 t1)
                         (fxxor t0 tmp)))))
    (fl-OF)))
```

The exception:

```
Unhandled exception
 Condition components:
   1. &compiler-internal-error
   2. &library: compiler
   3. &module: assemble-sources
   4. &who: xorl
   5. &message: "invalid instruction operands"
   6. &irritants: ((xorl 144 %ebx) 144 %ebx)
```

**Comment by marcomaggi** [comment]
I cannot reproduce it.  If I run this program:

```
#!r6rs
(import (rnrs)
  (only (vicare) debug-print))
(define (foo) 0)
(debug-print
 ((lambda ()
    (let* ((t0 (foo))
	   (t1 18)
	   (tmp (fx- t0 t1))
	   (fl-OF (lambda ()
		    (fxand (fxxor t0 t1)
			   (fxxor t0 tmp)))))
      (fl-OF)))))
```

I see `(2)` as output.  If I print the assembly generated by the `lambda` I see indeed an instruction `(xorl 144 %ebx)` but it seems it is compiled correctly.

**Comment by weinholt** [comment]
Forgot to mention that the test works in the repl, where foo is not inlineable. Here's a program that triggers it for me:

```Scheme
#!r6rs
(import (rnrs)
        (rnrs eval)
        (only (vicare) debug-print))
(define f
  (eval '(lambda (x)
           (let* ((t0 x)
                  (t1 18)
                  (tmp (fx- t0 t1))
                  (fl-OF (lambda ()
                           (fxand (fxxor t0 t1)
                                  (fxxor t0 tmp)))))
             (fl-OF)))
        (environment '(rnrs))))
(debug-print
 (f 0))
```

**Comment by weinholt** [comment]
I added it to a test branch, the error is at line 5315:

https://travis-ci.org/weinholt/zabavno/jobs/198661634

**Comment by marcomaggi** [comment]
I have  possible fix in the head of branch `issue-094.marcomaggi-2017-02-06`.

**Comment by weinholt** [comment]
I've checked and can confirm that your fix solves the issue.

**Comment by marcomaggi** [comment]
Thanks.  I will merge into `master` and upload a new tarball on Bitbucket.
