### ISSUE TITLE
cond without an else clause produces no values

### ISSUE THREAD

**Issue by weinholt** [marcomaggi/vicare#95]
I am using Vicare Scheme 0.4d1.1 on Debian GNU/Linux 8.7 amd64.

The cond syntax is not behaving properly when there is no else clause. The following expressions should all return 1:

```
Vicare Scheme version 0.4d1.1, 64-bit
Build 2017-02-15

Copyright (c) 2006-2010 Abdulaziz Ghuloum and contributors
Copyright (c) 2011-2016 Marco Maggi and contributors

vicare> (cond (#t 1))
vicare> (cond (1))
vicare> (cond (else 1))
$1 = 1
```

**Comment by marcomaggi** [comment]
This is on purpose.  It is explained in the [devlog](http://marcomaggi.github.io/weblog/2016-Dec-05.html).  I have not yet properly documented these changes.  Sorry.
